DROP TABLE IF EXISTS EMPLOYEE_DETAILS;

CREATE TABLE EMPLOYEE_DETAILS (
  EMPLOYEE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL_ID VARCHAR(250),
  PHONE_NUMBER NUMBER(15,0)
);

INSERT INTO EMPLOYEE_DETAILS (FIRST_NAME, LAST_NAME, EMAIL_ID, PHONE_NUMBER) VALUES
  ('Test', 'T', 'test@test.com', 1234567899);
  
 COMMIT;